### ISSUE TITLE
website categories

### ISSUE THREAD

**Issue by RachelF** [GSA/touchpoints#1051]
I noticed the dropdown for the "type of site" category no longer includes the category for "informational" sites. Instead, I see "custom - informational (not transactional) site"

Can you please remove the "custom" designation from the "informational" category when you get a chance? Thanks!

**Comment by ryanwoldatwork** [comment]
Yep!

<img width="711" alt="Screen Shot 2022-11-23 at 8 59 12 AM" src="https://user-images.githubusercontent.com/64987852/203605587-6ff83312-a86b-4fcb-b1d6-a93ab64b368f.png">
