### ISSUE TITLE
Adding manager name to drop down

### ISSUE THREAD

**Issue by anatecture** [GSA/touchpoints#1124]
**General user story:** 
As a user, I need to be able to add new website managers in free text to the website manager field. Otherwise, I have to go through this open backlog to get those names added, which is inefficient. 

**Specific request**
Please add the name provided in the Primary website contact email field to the Additional website contacts dropdown for realestatesales.gov.

**Comment by ryanwoldatwork** [comment]
Hi @anatecture,

Is this about ensuring the Primary Contact is also listed as an "Additional Contact" ? 
Or is this about getting a new username added to the dropdown? The Additional website dropdown is populated with existing Touchpoints users. A user would need to sign into Touchpoints to be listed there, whereas a Primary Contact can currently be free text, and may not need to be a Touchpoints user (this will likely change in the future).

<img width="552" alt="tp" src="https://user-images.githubusercontent.com/64987852/221941892-1842e749-dac3-4739-a910-f4e45ad03e24.png">

Happy to chat about this more,

**Comment by ryanwoldatwork** [comment]
Hi @anatecture,

Thanks for the chat yesterday!

Soon, the change below will be deployed, allowing a user to invite a colleague who hasn't yet signed up for Touchpoints.
The `invite` page will now be accessible in another place besides the Form's Permissions' tab, which isn't line-of-sight (nor intuitive), from the Websites page.

<img width="608" alt="Screen Shot 2023-03-01 at 10 37 52 AM" src="https://user-images.githubusercontent.com/64987852/222233985-a85a5d0d-41b4-4230-8b73-da43f0cb61bf.png">
