### ISSUE TITLE
[wiki] update links

### ISSUE THREAD

**Issue by lisac-usds** [GSA/touchpoints#1163]
This repo's wiki was **very** instructive for me - thank you for putting that together.

I encountered a few links in the wiki that would not resolve for me. Below is a list of the respective pages of the links and proposed updates. 

Thanks for your work on Touchpoints!

----

1. Page/Section: Home -> [Technical Reference for Developers who contribute](https://github.com/GSA/touchpoints/wiki#technical-reference-for-developers-who-contribute)
   - Link label: `Deployment`
   - Link url: https://github.com/GSA/touchpoints/wiki/Deployment
   - Proposed Link url:   https://github.com/GSA/touchpoints/wiki/Continuous-Integration   or  https://github.com/GSA/touchpoints/wiki/Configuration-Management-Plan   or  https://github.com/GSA/touchpoints/wiki/Operations#deployment
2. Page/Section: Personas -> [How do Personas map to Roles & Permissions?](https://github.com/GSA/touchpoints/wiki/Personas#how-do-personas-map-to-roles--permissions
)
   - Link label: `Permissions`
   - Link url: https://github.com/GSA/touchpoints/wiki/PERMISSIONS.md
   - Proposed Link url:   https://github.com/GSA/touchpoints/wiki/Permissions 
3. Page/Section: [Permissions]( https://github.com/GSA/touchpoints/wiki/Permissions ) 
   - Link label: `Use Cases`
   - Link url: https://github.com/GSA/touchpoints/wiki/USE_CASES.md
   - Proposed Link url: https://github.com/GSA/touchpoints/wiki/Use-Cases
4. Page/Section: [Data Model](https://github.com/GSA/touchpoints/wiki/Data-Model)
   - Link label: `db/schema.rb` 
   - Link url: https://github.com/GSA/db/schema.rb
   - Proposed Link url: https://github.com/GSA/touchpoints/blob/main/db/schema.rb 
5. Page/Section: Compliance -> [Artifacts](https://github.com/GSA/touchpoints/wiki/Compliance#artifacts)
   - Link label: `Privacy Impact Assessment`
   - Link url: https://www.gsa.gov/cdnstatic/Touchpoint%20PIA_siged_1042019_webversion.pdf
   - Proposed Link url: I don't have a proposal. the current link shows me a 404 status code.
6. Page/Section: [System Maintenance](https://github.com/GSA/touchpoints/wiki/System-Maintenance)
   - Link label: `System Status Dashboard`
   - Link url: https://status.uptrends.com/e28cdceee0ca40319fd20233f48f5a88
   - Proposed Link url: current link shows me a 404 status code, although it could be that the page exists and I'm not authorized 
7. Page/Section: Touchpoints Onboarding Questions -> [A-11 Readiness](https://github.com/GSA/touchpoints/wiki/Touchpoints-Onboarding-Questions#a-11-readiness-if-applicable)
   - Link label: `guidance`
   - Link url: https://github.com/GSA/touchpoints/wiki/A-11-Guidance 
   - Proposed Link url: https://github.com/GSA/touchpoints/wiki/A-11-PRA-Guidance

**Comment by ryanwoldatwork** [comment]
hi @lisac-usds - these updates have been made in the wiki.

Thanks!!
