### ISSUE TITLE
Missing input label (for #fba_directive text input)

### ISSUE THREAD

**Issue by qjac** [GSA/touchpoints#1190]
[WAVE](https://wave.webaim.org/) is generating a Major Error: Missing form label on a text input.

`<input type="text" name="fba_directive" id="fba_directive" aria-hidden="true" style="display: none !important;" tabindex="-1" autocomplete="off">`

**Comment by ryanwoldatwork** [comment]
This is a known, reported finding.
I don't plan to address this at this time. Happy to chat about it though.
