### ISSUE TITLE
Close button needs an accessible label

### ISSUE THREAD

**Issue by qjac** [GSA/touchpoints#1191]
The Close button is currently labeled 'x' which does not convey the function of the interactive control. Add link text, aria-label, or aria-labelledby that accurately describes the functionality of the close link.

Expected Results: Screenreader users should hear "Close modal" (or similar language) when the close button is focused.

![touchpoints-rotor-links-close-x](https://github.com/GSA/touchpoints/assets/11020538/70fd6523-c4e6-4394-a50b-f611c7d7943e)

**Comment by ryanwoldatwork** [comment]
Updated: `<a class="fba-modal-close" type="button" href="#" aria-label="Close this window">×</a>`
