### ISSUE TITLE
Embedded flag icon breaks with CSP

### ISSUE THREAD

**Issue by okkays** [GSA/touchpoints#1277]
Hello - let me know if I should direct this report somewhere else 😄 

Our application ([DOJ CRT's Civil Rights Portal](github.com/usdoj-crt/crt-portal/)) has a content security policy that disallows data URIs [for security reasons](https://security.stackexchange.com/a/95011) (we have to be conservative with our CSP 😅)

[A recent change](https://github.com/GSA/touchpoints/pull/1268/files#diff-9a2ba1cc686be8a25578f5656f76fb763fb8e5397fb172a2d0791546d39e4891) to the touchpoints footer flag image embeds it using a data uri which, in combination with that CSP, prevents browsers from loading the flag.

After some effort, I can't find a clean way to fix this from our side (especially given the content is generated dynamically).

So I was wondering - have you run into this with other customers / any suggestions as to how to fix this?

Thanks!

**Comment by ryanwoldatwork** [comment]
Hi @okkays, 

The change has been reverted, and an image is loading again.
There are CSP changes that can be made on each website, and ideally, this will be revisited as an optional feature, along with CSP guidance.

**Comment by okkays** [comment]
Thanks for the quick fix - can confirm it's working! sorry for the trouble 😅
