### ISSUE TITLE
Radio buttons overlaps question text

### ISSUE THREAD

**Issue by jhutchison-opm** [GSA/touchpoints#1295]
FYI, this is affecting our live survey on OPM.gov

<img width="401" alt="image" src="https://github.com/GSA/touchpoints/assets/149509859/706a7b31-b74b-41a8-90dc-8a96e84c889d">

I can't tell what's causing this issue, but it looks like adding `clear: both;` to `.question-options` should resolve this.

<img width="412" alt="image" src="https://github.com/GSA/touchpoints/assets/149509859/59a1cb41-4aab-4760-b757-7e1112515188">

**Update: Looks like theres a float on USWDS `.usa-legend` coming from our stylesheet that isn't cleared and is leaking into the survey

**Comment by ryanwoldatwork** [comment]
Hi @jhutchison-opm,

I'm closing this issue, because this was related to existing website styles conflicting, and we have discussed this elsewhere.

**Comment by jhutchison-opm** [comment]
Fair enough. Although, it may be worth looking into a way to encapsulate the styles of Touchpoints so that they can't be (easily/accidentally?) overwritten by the host site. Especially since, I suspect, there will often be a collision of class names.

**Comment by ryanwoldatwork** [comment]
Hi @jhutchison-opm - good thought. 
Touchpoints uses USDWS 2.10.x styles for the embed, and those styles are namespaced within the form.

Here's some more info on that - https://github.com/GSA/touchpoints/wiki/Form-Markup.

If there are any outstanding issues, I'd be happy to work with you on specifics.

**Comment by jhutchison-opm** [comment]
Right, but because the elements are actually added to the page, any styles that aren't specifically overwritten, or are higher specificity than the Touchpoints styles, leak into the form. And most of the elements of the form aren't don't use the namespace to display the styles, they're just using the USWDS class names. The problem is that it's difficult to debug given that you'd need to verify that Touchpoints is working correctly on every page its embedded on. 

Currently on the OPM.gov homepage, for example, you can scroll up within the survey causing the form to be half hidden. Again, this appears to be because styles from the OPM site are leaking into the form styles. To be fair, I'd argue that styling elements like in the screenshot isn't great CSS hygiene, but I suspect the level of effort to debug and fix issues like that in legacy codebases would be fairly high.

![image](https://github.com/GSA/touchpoints/assets/149509859/5481e289-8944-449c-840b-64a31053c866)

That said, I suspect the only real way to prevent this from happening would be to use an iframe or have some sort of high specificity CSS reset.

**Comment by jhutchison-opm** [comment]
And ditto, I'm always happy to chat!
