### ISSUE TITLE
Un-scoped .usa-skipnav is causing breaking changes

### ISSUE THREAD

**Issue by lordscarlet** [GSA/touchpoints#1362]
https://github.com/GSA/touchpoints/commit/ce62b4590d903731560037c700b84349dbb6bf74#r138594917

By making this change, this setting now overrides existing styles scoped to `.usa-skipnav`. This is causing visual errors on production websites.

**Comment by ryanwoldatwork** [comment]
Hi @lordscarlet - thanks. Will pursue a resolution here.

Do you have a sample url?

**Comment by ryanwoldatwork** [comment]
@lordscarlet - the global, unscoped .usa.skipnav styles were removed yesterday, so this should be resolved.

**Comment by ryanwoldatwork** [comment]
@lordscarlet - I wanted to see if you've had a chance to ensure this is working on your side.
