### ISSUE TITLE
CX Reporting Improvements

### ISSUE THREAD

**Issue by ryanwoldatwork** [GSA/touchpoints#1595]
During quarterly reporting, HISPs were downloading their A-11 CSV for their quarterly reporting.

CSV is of all responses.

There is no date marker.

To isolate responses for the quarter, they need to find the start and end IDs for quarter in the larger/more complete CSV download; filter to the IDs for the quarter. (This leads to lots of manual steps and human errors)

* HISP can download A-11 CSV by quarter - so one download button per quarter. CSV is broken down by quarter
* HISP can download A-11 CSV with an added column for the date of each response. 
* * HISP can filter to the quarter, saved the CSV as a new CSV and upload (they would need to delete rows and 1 column tpo get to the formatting needed for reporting).

### Timeline

Tested and live before end of Sept 2024. 
Oct 1-30 is reporting period for FY24 Q4.

**Comment by ryanwoldatwork** [comment]
@BinFZheng -

One way to sort by date, is to add a datetime field to the CX_Responses table. HISP agencies would need to add this to their uploads. A Touchpoints table, API and exports would need a minor update.

And, given CxResponse records are created from a CxCollectionDetailUpload csv, there should be a way to determine when the CxResponses were created (by the date of their CxCollectionDetail upload). This is more of a workaround, but something to keep in mind.

**Comment by BinFZheng** [comment]
@ryanwoldatwork  Answering your questions here: 

1.	What data do you want to download by quarter? 
(I'm assuming the big CxRespones table, or did you also want CX Collections and CX Collection Details, and

Referencing the Export A11-v2 Response to CSV option on the A-11 surveys on Touchpoints. This would be the big CX Response table. The HISPs need this table by quarter so they don't have to break it up themselves or they need an easy way to group the responses/rows into quarter (currently unable to do inside the CSV). 

2.	The current CX Detail Upload file does not include a timestamp for incoming, upload CSV responses.   
Do you anticipate asking this of HISPs? (and updating the Touchpoints CSV upload (and API) with an additional field)

I think if we go with adding a column for time sample in the Export A11-v2 Response to CSV - then Touchpoints/HISPs will have to delete rows, delete 1 column, and then upload the CSV. That's fine if that's the most elegant solution. I don't anticipate asking other HISPs or Private Platform/HISPs of changing the dataset format in CSV that they upload (i.e. we're keeping to the columns we have now). Certainly some loss here but changing those requirements will open a whole other pandora's box. 

The request here is strictly to make it easier for the Touchpoints/HISPs to have the correct download to upload the CSV each quarter.
