### ISSUE TITLE
Adding columns from A-11 CSV outputs to main CSV table?

### ISSUE THREAD

**Issue by BinFZheng** [GSA/touchpoints#1596]
Related to this data output issue: https://github.com/GSA/touchpoints/issues/1595

For the TSA passenger screening survey - they download both their main CSV and the A-11 CSV. Afterward, they need to join the two tables so they can grab the columns from the A-11 CSV tables (1s and 0s for the individual driver statement). 
- HISP does not have capacity/script to break out the driver column in the main CSV themselves 
- So they do the joining themselves outside of Touchpoints - which adds an extra step
- This could be quite common with other low capacity team (i.e. they don't have data scientists nor management analyst who can do this for them). 
- The current main CSV outputs assume that agencies can break out the driver columns themselves. 

Question Touchpoints team - 
- Do we want to add the separate driver columns to the main download?
- If we do it for TSA, we would do it for all agencies with A-11 surveys. 

Let's chat on Thursday, Sept 5 to see if we want to go in a particular direction.

**Comment by BinFZheng** [comment]
Effectively - the ask: Can we and is it sensible to add the columns from Export A11-v2 Responses to CSV to the end of All Responses here? This would help TSA and other customers from having to join tables and/or write script to break out the categorical driver response col in All Responses into individual driver columns. 

![Screenshot 2024-09-06 164312](https://github.com/user-attachments/assets/9a4fa330-31b9-49db-8f8b-edfb37599477)

**Comment by ryanwoldatwork** [comment]
@BinFZheng - how about something like:

### Add a new button

![Screenshot 2024-09-06 at 3 21 44 PM](https://github.com/user-attachments/assets/ab9d573c-532b-40a8-b752-f5f1a16752d6)


### Add columns to the specific CSV

![WIDE](https://github.com/user-attachments/assets/8e74c461-4a91-4691-a635-79d53cd95d56)

--

I started with this, as to not impact the standard form .csv export code.
