### ISSUE TITLE
Sharing service stage table 

### ISSUE THREAD

**Issue by BinFZheng** [GSA/touchpoints#1598]
Please share the service stage data table with me. 
Please let me know how I can navigate to it on my Touchpoints admin account.  

I want to take a look and pick out a few Services to start working with on improving their inputs there. Thanks! 

Deadline - Sept 15, 2024

**Comment by ryanwoldatwork** [comment]
hi @BinFZheng - there hasn't been much done in terms of that data yet.  Let's chat.

Each Service has a Service Stages tab. In that tab, Service Stages for a specific Service can be edited. These objects are very basic for now, but are intended to be the foundations of something like BPMN model objects.

I'll see about getting a basic export going asap.

**Comment by ryanwoldatwork** [comment]
@BinFZheng - for visibility https://github.com/GSA/touchpoints/pull/1600

**Comment by BinFZheng** [comment]
@ryanwoldatwork Running into a "something went wrong" page when I tried to download: 

![Screenshot 2024-09-09 150844](https://github.com/user-attachments/assets/f922720b-b58c-42d7-95f2-0427f0d8454d)

**Comment by BinFZheng** [comment]
@ryanwoldatwork I created this graphic with FIGMA. Here's how the final data viz/product related to the service stage clean-up should ultimately look like. It'll be through Tableau functionalities but want to show you the vision. Also, this is based on your idea for service stage level tracking, etc.  

![service stage graphic](https://github.com/user-attachments/assets/e0d2fbc4-6abc-4b45-be1f-615adfd234f6)

**Comment by ryanwoldatwork** [comment]
@BinFZheng - the download has been fixed.

There were a couple orphaned records from testing.

**Comment by ryanwoldatwork** [comment]
@BinFZheng - thanks for sharing the sketch! looking good!

if i understand it correctly, that is displaying 4 different feedback services within a single journey.

👏

**Comment by BinFZheng** [comment]
@ryanwoldatwork I should have added the service name at top. It would show four different surveys, each at a different touchpoint -- all within a single customer journey of a service.

**Comment by BinFZheng** [comment]
For discussion at next meeting, @ryanwoldatwork  - 

<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/BZheng/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/BZheng/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">


Fields | For discussion
-- | --
id | Keep
name | Keep
description | Do we need this?
service_id | Keep
notes | Do we need this?
time | Keep
position | Keep
total_eligible_population | Do we need this?
created_at | Keep
updated_at | Keep
persona_id | Do we need this?
service_name | Keep/move up
service_provider_id | Keep
service_provider_name | Keep



</body>

</html>

**Comment by ryanwoldatwork** [comment]
description is to describe the step; a place for text

notes is a place for text.. it could go.. but is useful in my experience

total_eligible_population could probably go away, but then it should live on a service, or at a "process" level.  eg: how many Veterans eligible for benefits, vs how many OSHA clients vs how many TSA travelers, etc.

persona_id is needed in order to define who (which persona) is for a stage.   eg: which persona is referenced in a business process? across business processes?

### References

* https://en.wikipedia.org/wiki/Business_Process_Model_and_Notation
* https://en.wikipedia.org/wiki/Business_process_modeling
