### ISSUE TITLE
Sunset the Digital Registry

### ISSUE THREAD

**Issue by ryanwoldatwork** [GSA/touchpoints#1610]
Acceptance Criteria

* The Digital Registry Touchpoints application is no longer accessible by the public by October 31, 2024
* Data is archived

**Comment by ryanwoldatwork** [comment]
https://github.com/GSA/touchpoints/pull/1611

**Comment by BinFZheng** [comment]
I have a meeting with Justin Grimes next week to catch up on the context for this issue.

**Comment by ryanwoldatwork** [comment]
The public-facing page of the Registry has been updated.

https://touchpoints.app.cloud.gov/registry
