### ISSUE TITLE
New Touchpoints acct creation - 

### ISSUE THREAD

**Issue by BinFZheng** [GSA/touchpoints#1635]
John Schultz - is our new intern on the CX team. John.T.Schultz@omb.eop.gov 

I'll supervise John in updating records and implement the FY24 Q4 data collection process. 

- [x] Please give him the same Touchpoints admin/mgr access as I have. 

In addition, I had John create an account and play around with the FORM feature, i.e. creating test surveys. His account now has this view when he clicks into the Performance tab: 

![touchpoints_screenshot](https://github.com/user-attachments/assets/6e4e5b29-35d4-4b6b-83a2-e37d4f435c67)
I know I am supposed to see the tally table. Is he supposed to see it under a regular account? Do other HISP account holders also have the table under Perfornance, then A-11v2 Tab?

**Comment by BinFZheng** [comment]
In addition, please confirm if tamisha_tenorio@btfa.gov 's Touchpoints account is active? 

- [ ] tamisha_tenorio@btfa.gov acct active?

**Comment by ryanwoldatwork** [comment]
Tamisha's account has been reactivated.
Users get a flash message instructing them to email when logging in.
