### ISSUE TITLE
Troubleshooting FY24 Q4 CX Data Collection Reporting (from Oct 1 - 30, 2024) 

### ISSUE THREAD

**Issue by BinFZheng** [GSA/touchpoints#1642]
HI all, I am starting this thread to document and resolve any Touchpoints tasks and troubleshooting related to FY24 Q4 CX Data Collection. 

The survey responses will be from: July 1, 2024 to Sept 30, 2024
The reporting period will be from: Oct 1, 2024 to Oct 31, 2024 
We will be expecting reporting from more than 50+ services this round. 

To start: 
- [x] Create 71 Collection Records for 71 services for FY24 Q4 (completed by John Schultz) 
- [x] Check FY24 Q4 records for duplicates and POCs - (completed by Bin)

**Comment by BinFZheng** [comment]
- [ ] @ryanwoldatwork  can you add John Schultz to this issue and the touchpoints thread overall? (jtsomb)

**Comment by ryanwoldatwork** [comment]
Hi @BinFZheng 

No, I can't add John. He's not in the org or on this team.
He can view this URL and participate though.

**Comment by BinFZheng** [comment]
@ryanwoldatwork Thanks! Let me check with Ivan to see if he can get John a GSA license/seat. I think that's how I got access. I need John to support with filling out tickets, running data analysis with Touchpoints, etc. so it would be good for him to have commenting power.

**Comment by ryanwoldatwork** [comment]
He can comment without a seat.

**Comment by jtsomb** [comment]
Hi! This is John

**Comment by BinFZheng** [comment]
@ryanwoldatwork Here is a list of the unique Data POCs of the 71 CX Collection records for FY24 Q4. Thanks! 

- [ ] Review list for inactive accounts 
- [ ] Activate inactive accounts

ackerman.elizabeth.c@dol.gov
annie.ingram@fema.dhs.gov
brian.schwind@usda.gov
charlene.toledo@bia.gov
charles.thomas1@uspto.gov
christine.o'neill@sba.gov
david.j.lunsford@irs.gov
eric.christiansen@ssa.gov
ethan.moore@cms.hhs.gov
etienna.winzer@ed.gov
frank.carter2@va.gov
goodgoldre@state.gov
jacob.a.wright@census.gov
janelle.smith@usda.gov
janet.pence@cbp.dhs.gov
jennifer.dempsey@usda.gov
joseph.p.carter@hud.gov
kendra_collat@nps.gov
kistler.benjamin.j@dol.gov
kittrell.danielle.h@dol.gov
lauren.rayburn@usda.gov
maggie.a.larkin@uscis.dhs.gov
mansur.leyla@dol.gov
marietta.jelks@gsa.gov
markovitzp@cdfi.treas.gov
matjohnson@usaid.gov
matt.cesnik@opm.gov
matthew.garber@fiscal.treasury.gov
maureen.e.earley@omb.eop.gov
michele.broccolino@cms.hhs.gov
mjangi@usaid.gov
nantaisjd@state.gov
nicholas_solomon@nps.gov
oconnor.madeline.m@dol.gov
patrick.dunn@tsa.dhs.gov
roy_hewitt@fws.gov
sarah.spradlin-knippenberg@associates.tsa.dhs.gov
shadonna.l.small@uscis.dhs.gov
stephen.f.nemeth4.civ@mail.mil
tamisha_tenorio@btfa.gov
tanesha.espey@usda.gov
thomas.pasakarnis@va.gov
todd.w.rubin2@omb.eop.gov
toni.krasnic@uspto.gov

**Comment by BinFZheng** [comment]
@ryanwoldatwork Want to confirm the options for A-11 data download for Touchpoints users here as we got a few inquiries on this from folks:

**Comment by BinFZheng** [comment]
@ryanwoldatwork  This is the updated instruction we give HISP for data download/quarterly reporting: 

Exporting Response CSVs for a survey deployed on Touchpoints 
•	Touchpoints provides a few export options to access the responses to your survey. The options are available at the bottom of the Response subtab in Survey Form. 
IMAGE 
•	The export options are: 
o	Export All Reponses to CSV 
o	Export A11-v2 Responses to CSV 
o	Export Form + A11-v2 Responses to CSV 
•	Previously, we had asked Touchpoints users to use Export A11-v2 Responses to download a CSV that meet all formatting requirements. However, the CSV does not segment the responses by quarter, which can lead to duplicate reporting. For now, DO NOT USE Export A11-v2 Responses. 
•	Use EXPORT Form + A11-v2 Responses to CSV, which will give you a download of all the A-11 fields required for reporting, and all the fields for the remaining question on your survey, including a “CREATED AT” field. When you click on the button, Touchpoints will actually email you a link with the CSV for download. 
 
•	The email looks like this: 
IMAGE 
•	With EXPORT Form + A11-v2 Responses to CSV, you will need to clean up the CSV a little to get it ready for quarterly reporting. Principally, the tasks are: 
o	DELETE fields that are not required (if your survey has additional questions, such as user types, use cases, etc. and/or metadata fields on the respondents). 
o	DELETE responses/rows that are outside the range of the reporting period using the CREATED AT field. The CREATED AT field would also need to be deleted. 
o	For exact field names, order of fields on the CSV, total number of fields, etc., see section on “CHECKLIST FOR THE RESPONSE CSV” in the next section on this guide.

**Comment by BinFZheng** [comment]
[How-To_Format your Customer Feedback Data_10.16.2024 update.docx](https://github.com/user-attachments/files/17397760/How-To_Format.your.Customer.Feedback.Data_10.16.2024.update.docx)

**Comment by ryanwoldatwork** [comment]
@BinFZheng - would you like this document linked somewhere? or posted in the wiki?

**Comment by ryanwoldatwork** [comment]
@BinFZheng,

1. Total collections and the filtered counts are showing:

![image](https://github.com/user-attachments/assets/01e41d36-97ab-45ac-a951-0264268a46ec)

2. The "Download CX Responses" button will pass the year and quarter filtered, returning only the Responses for the Collections and Collection Detail

**Comment by BinFZheng** [comment]
@ryanwoldatwork Going to close this comment as FY24 Q4 reporting is closed. I am going to start new threads as needed. Thanks!
