### ISSUE TITLE
Deprecate CX Collections (version 1)

### ISSUE THREAD

**Issue by ryanwoldatwork** [GSA/touchpoints#1645]
Maintain CX Collections version 2 features.

* [x] archive the CX Collections data, share it with @BinFZheng
* [x] remove the features from Touchpoints
  * [x] remove `collections` table
  * [x] remove `cx_collection_details` table

**Comment by BinFZheng** [comment]
- [ ] Bin - CSV to Ivan/S3 folder for Resources tab on p.gov/cx

**Comment by BinFZheng** [comment]
@ryanwoldatwork Did you share the final CSVs from the old A-11 Collections - I want to make sure it is archived in the old links for P.gov/cx (under Resources - https://www.performance.gov/cx/resources/). Thanks!
