### ISSUE TITLE
Adding "active" tag to list of service within page for service provider

### ISSUE THREAD

**Issue by BinFZheng** [GSA/touchpoints#1687]
@ryanwoldatwork This is worth a discussion on what is best/most elegant way to do this. 

Under page for each service provider, there is list of services under that service provider. 

Current view: 
![active service tag](https://github.com/user-attachments/assets/fc44cb9d-6bc4-4e4d-ae97-0d83ee9e5c0c)

Desired view should probably use the inactive? field - that's what I have been using to track active service versus retired service. 
- [ ] Replace "status" with "inactive" field?

**Comment by BinFZheng** [comment]
Should be tagged as cx-data-collection

**Comment by ryanwoldatwork** [comment]
https://github.com/GSA/touchpoints/pull/1696

**Comment by ryanwoldatwork** [comment]
Hi @BinFZheng, 

`previously_reported` has been added to the Service listing table:

![Screenshot 2024-11-18 at 4 07 39 PM](https://github.com/user-attachments/assets/48d67ea1-a4e1-4375-bda9-829d6d74bf0a)
