### ISSUE TITLE
feature request for in-line script

### ISSUE THREAD

**Issue by LindsayYoung** [GSA/touchpoints#234]
We are adding touch points for civilrights.justice.gov. With our CSP policy we want nonces for any inline javascript or have javascript come from a secure source. (We don't want to introduce unsafe-inline execution of scripts.)

We are using the pre-approved open-ended form. The way that characters remaining script is getting flagged as an inline script even though it is coming from the touchpoints fille, which we have on our CSP allow list. 

Could the default script for characters remaining be implemented in such a way that it isn't implemented as an inline script?

In the meantime, I will see if we can customize our snippet in the touchpoints console to not include character count. But, wanted to flag this because I would imagine it will be an issue other site have too. 

Thank you!

**Comment by ryanwoldatwork** [comment]
Hi @LindsayYoung - thank you for this feature request. I've captured it in our product backlog in Trello, and will do some research in terms of scoping and prioritization. We are currently mid-sprint, and our next iteration begins June 8.

**Comment by LindsayYoung** [comment]
Thank you!!

**Comment by ryanwoldatwork** [comment]
WIP open here: https://github.com/GSA/touchpoints/pull/235

**Comment by ryanwoldatwork** [comment]
Hi @LindsayYoung, 

Touchpoints now offers an integrity hash that can be included for an embed script.

⚠️  Important note ⚠️

Changing any aspect of the Form's display will change the Form's integrity hash checksum.

So, if a form is deployed with an integrity hash, and then the Form is changed, the Form's dynamically generated javascript content's will change, and thus the hash will change too.  

When the hash changes, any scripts that are deployed would essentially become invalid. Just something to be aware of.

---

![hash](https://user-images.githubusercontent.com/64987852/112891035-7c4a5700-908c-11eb-96f6-a6ff54ceb3de.png)


## Reference

* https://developer.mozilla.org/en-US/docs/Web/Security/Subresource_Integrity

**Comment by LindsayYoung** [comment]
Thank you!

**Comment by ryanwoldatwork** [comment]
With an `integrity` attribute now available, optionally, I am closing this issue.

Please re-open this issues if there are any outstanding or follow-up concerns.

Thanks!
