### ISSUE TITLE
Retrieve responses using only GET

### ISSUE THREAD

**Issue by gnieboer** [GSA/touchpoints#269]
To introduce feedback results into a data science pipeline, it would be helpful if the CSV data could be retrieved in a more automated / open fashion as a secondary option.

Example URL: https://touchpoints.app.cloud.gov/admin/forms/4fafafaf/responses/export_submissions?start_date=2019-10-10&end_date=2019-10-17

The "Export" button shows a similar URL, but it cannot be directly accessed as it it utilizes a Ruby-specific Action Cable / Subscription / WebSocket model.  The API would not need to be complex for our needs, just start and end date with the survey ID.

**Comment by ryanwoldatwork** [comment]
thanks @gnieboer - I'll run this through our iteration planning process and provide updates here.

* [ ] design the endpoint parameters (can likely use something similar to what exists)
* [ ] authenticate API requests

--

As an alternative, would it be possible (and useful) to push the data to somewhere to you on a regular basis?

**Comment by gnieboer** [comment]
If it could be pushed to a OneDrive or Sharepoint Online endpoint URL, that would feed nicely as we could then automate the process from the "file arrived" event.
Email would be a secondary option (setup to a specific email address at a specific interval), we'd need to explore setting up a dedicated receiver email address and automation to pull the file from the email, so it might be a bit trickier but still possible.

**Comment by ryanwoldatwork** [comment]
Hi @gnieboer - I could see pushing a data file to an endpoint URL. 

How often would this need to occur?
What file format? CSV? JSON? other?

**Comment by gnieboer** [comment]
max: Daily, min: Weekly
Pretty much any standard format would be fine.  CSV is probably simplest, but we could parse it from JSON as well.  Anything that R or Power BI can handle would work for us.

**Comment by ryanwoldatwork** [comment]
@gnieboer - We'll be able to turn around the `GET` endpoint much sooner than the automated auth, which represents a change to the system's boundaries.

**Comment by ryanwoldatwork** [comment]
@gnieboer - A .csv can now be retrieved with `GET` using the `.csv` endpoint.

At the bottom the Responses page, the export button in the UI queues the report using a `.json` endpoint.
The `.csv` endpoint can be accessed directly.

An example of the .json URL is `https://touchpoints.app.cloud.gov/admin/forms/UUID/export_submissions.json?start_date=2018-10-01`.

But the .csv URL is An example of the .json URL is https://touchpoints.app.cloud.gov/admin/forms/UUID/`export_submissions.csv`?start_date=2018-10-01.
