### ISSUE TITLE
Investigate font-size and spacing issues when a form is embedded

### ISSUE THREAD

**Issue by ryanwoldatwork** [GSA/touchpoints#270]
# Story

As a site owner,
I want my Touchpoint form to display the same as it does in the preview,
So that I can have consistency and control in site design.

# Acceptance

Given a Touchpoint form is embedded on the client site, p.gov,
When I view the touchpoint form on https://federalist-5232e959-9997-4f27-a482-3c19a3c9590f.app.cloud.gov/preview/gsa/interimperformance-dot-gov-2018/dashboard-updates/cx/
Then I see the form and it looks the same as it does in the Preview in Touchpoints (css style wise - minus the explicit customer overrides [like colors and button shapes])

**Comment by ryanwoldatwork** [comment]
The mis-styled form looks like:

![form-styles](https://user-images.githubusercontent.com/64987852/91477946-f0512200-e853-11ea-9ac7-b222047148b6.png)

But it should look like:

![form-preview](https://user-images.githubusercontent.com/64987852/91478005-0bbc2d00-e854-11ea-839d-e7c50e076efa.png)

**Comment by ryanwoldatwork** [comment]
The smaller fonts seem to be caused by `rem` CSS treatments for font-sizes and other attributes.

> When using rem units, the pixel size they translate to depends on the font size of the root element of the page, i.e. the html element. 

> When using em units, the pixel value you end up with is a multiplication of the font size on the element being styled.

via https://webdesign.tutsplus.com/tutorials/comprehensive-guide-when-to-use-em-vs-rem--cms-23984

**Comment by ryanwoldatwork** [comment]
![tiny-button](https://user-images.githubusercontent.com/64987852/101976685-9dca2480-3bfc-11eb-86e9-98c924823622.png)

Viewable here: https://rd.usda.gov/resources/regulations/program-regulations

**Comment by mejiaj** [comment]
@ryanwoldatwork is there a way to disable the inline styles? Either by removing them or via a technique like [Remove inline styles](https://css-tricks.com/snippets/javascript/remove-inline-styles/) from CSS-Tricks.


The small font-size `1rem` isn't working as you might expect because html has a px font-size of `10px`. Meaning `1rem = 10px`. If you were to set it to browser default 16, then you might have something like you would expect.

**Comment by ryanwoldatwork** [comment]
@mejiaj - yes, there is a way to toggle off inline styles in Touchpoints. In that case, the tab and such rely on USWDS styles for proper display.   Unfortunately, some sites, like the sample USDA site for this issue, doesn't use USWDS styles either.

🤔

**Comment by MaroyaF** [comment]
@ryanwoldatwork can this be closed

**Comment by ryanwoldatwork** [comment]
closing as styles are now namespaced like `fba-*`, eg: `fba-usa-modal`
