### ISSUE TITLE
dol.gov not recognized domain

### ISSUE THREAD

**Issue by dhborden** [GSA/touchpoints#31]
When I tried to sign up using my dol.gov email address, I got the following error message: •Organization dol.gov is not a valid organization - Please contact Feedback Analytics Team for assistance

**Comment by afomi** [comment]
@dhborden - thanks for getting in touch.

DOL is not currently onboarded to Touchpoints production.
However, the [Demo environment](https://touchpoints-demo.app.cloud.gov/) is available, and DOL is setup there. You will be able to sign up there with your @dol.gov address.

Any questions at all, please let me know.  I'll leave this issue open until Friday in case any follow ups.

**Comment by dhborden** [comment]
Hi Ryan,

I just tried to sign up on the demo environment but it tells me my
government email address is already in use. What can we do next?

Regards,
Doug

**Comment by afomi** [comment]
@dhborden - I sent you an email yesterday with information to access Demo.

Any questions, let us know at feedback-analytics@gsa.gov. Thanks!

**Comment by afomi** [comment]
@dhborden - thanks for confirming you can now access Demo.

Please give Touchpoints a try:

* Create a Service
* Create a Touchpoint with an A-11 Form for that Service
* Test a Submission

Any questions at all, let us know.

Ryan
c/o @GSA/feedback-analytics
