### ISSUE TITLE
Survey Editor – Bug when updating Question text

### ISSUE THREAD

**Issue by colinmurphy01** [GSA/touchpoints#435]
Steps to Reproduce
1. Edit question
2. Update question text
3. Hit Update Question
4. User is served an unstyled page with the question text updated + edit and delete buttons (this might be the issue)
5. As a user I hit the back button in the browser because I don't want to edit or delete
6. I'm taken back to survey form editor, question text isn't updated
7. I hit edit again, I find text is up to date
8. I hit cancel and return back to survey form editor
9. Text is updated

See screen recording.

https://user-images.githubusercontent.com/24654605/115411903-e05ec780-a1c1-11eb-95ca-255878b25f61.mov

**Comment by ryanwoldatwork** [comment]
Thanks @colinmurphy01! 

Noting this and will get this addressed soon.

**Comment by ryanwoldatwork** [comment]
Hi @colinmurphy01 - this is now resolved. 

Thank you for reporting this issue.
Please let me know if you have any questions at all.
