### ISSUE TITLE
Submission text truncation...

### ISSUE THREAD

**Issue by vdavez** [GSA/touchpoints#450]
When I'm in the web UI, I would love to be able to copy and paste from the response table, but the `_submissions` view truncates the text to 160 characters.

See https://github.com/GSA/touchpoints/blob/production/app/views/admin/submissions/_submissions.html.erb#L37

Is there a way to enable copy and pasting or to eliminate truncation?

**Comment by ryanwoldatwork** [comment]
@vdavez - thanks for asking. Let's chat.

The product started by showing the full text, but that is sometimes too large.
Maybe there's a setting to be had in the UI if toggled.

I'm noting for now and will be in touch soon.

Have you been able to use the API to capture the full text responses?

**Comment by vdavez** [comment]
I'm definitely able to get full text through the API or CSV export. But given the email notification flow, it'd be sweet to just have it in the UI. It's not a show stopper for me day to day, but it'd be a nice enhancement.

**Comment by ryanwoldatwork** [comment]
Would it be valuable to click through to a submission's details? And those details would contain the full text?

Or is this workflow based on copy/pasting many submissions at once from the table?

**Comment by vdavez** [comment]
Oh! That would be a great option. Especially if the detail view could then have a permanent URL for reference/sharing.

**Comment by ryanwoldatwork** [comment]
@vdavez - you can kick the tires on this at https://touchpoints-demo.app.cloud.gov/index.

Create a form and submit a response.
Or, let me know, and I'll add you to a test form with long-text responses.

![Screen Shot 2021-05-07 at 5 17 15 PM](https://user-images.githubusercontent.com/64987852/117519381-1b9a1e00-af58-11eb-8166-0430d2119b6d.png)

**Comment by ryanwoldatwork** [comment]
Any issues or questions regarding this feature, let me know!
