### ISSUE TITLE
Submissions Archive (i.e., hide, but not delete)

### ISSUE THREAD

**Issue by vdavez** [GSA/touchpoints#451]
As a Form Manager,
I want to be able to archive a submission,
So that I can retain the fact that the submission was made, but not delete it from the database.

**Comment by ryanwoldatwork** [comment]
Hi @vdavez - we're exploring whether and how to add state (statefulness) to each submission.

I'd like to learn more about your use case for archive.

* received
* archived

are two potential states or statuses a submission could have.

Do you see any need for other states?

**Comment by vdavez** [comment]
That's awesome. I can't think of any other potential states off hand. But I'll consider it!

**Comment by ryanwoldatwork** [comment]
Responses can now be Archived.

And, a Response now has a default state of `received`. A Form Manager may change the status of any given Response to `acknowledged`, `dispatched`, or `responded`.  This state is tracked in addition to `archived` or not.

![Uploading archive-a-response.png…]()

You can try this at https://touchpoints-demo.app.cloud.gov/index.

---

Archived responses will not show in the Responses list view by default, but you can pass an `?archived=1` to the page, or click the link in the display options to do that.

**Comment by vdavez** [comment]
This is *sweet*! From a UI perspective, I might put the responses above the form submission metadata. But otherwise, this is incredible.
