### ISSUE TITLE
Add field to customize success message heading

### ISSUE THREAD

**Issue by maya** [GSA/touchpoints#482]
I'd like to change "success" to other text

**Comment by ryanwoldatwork** [comment]
Hi @maya,

This can be done via the `../forms/:id/edit` page, about 3/4 down. We're planning to move this to the bottom of the Questions page.

<img width="584" alt="Screen Shot 2021-05-20 at 4 16 51 PM" src="https://user-images.githubusercontent.com/64987852/119060345-daa5fe80-b986-11eb-8399-01611f8c0846.png">

**Comment by maya** [comment]
Hey Ryan, it lets me update the body of the alert, not the heading which is what the issue is about. The heading I'm referring to is "Success" and that's not editable.

**Comment by ryanwoldatwork** [comment]
Hi @maya,

Can you check this out on the Edit page and let me know if it works for you?

![Uploading success-text-heading.png…]()

**Comment by maya** [comment]
Yes, this works, thanks!

<img width="1034" alt="Screen Shot 2021-05-24 at 5 27 05 PM" src="https://user-images.githubusercontent.com/5249443/119422215-6d130e80-bcb5-11eb-8cbd-fc85a7bca54a.png">
