### ISSUE TITLE
Text area field responses are unformatted (missing line breaks)

### ISSUE THREAD

**Issue by maya** [GSA/touchpoints#483]
Text comes in as a wall of text. I expect it to have the line breaks that I typed in

This is what I see
<img width="848" alt="Screen Shot 2021-05-20 at 8 40 08 PM" src="https://user-images.githubusercontent.com/5249443/119078813-c3c5d300-b9ab-11eb-8b91-956a1d376d9b.png">

But in the inspector, you can see the text has line breaks
<img width="886" alt="Screen Shot 2021-05-20 at 8 43 36 PM" src="https://user-images.githubusercontent.com/5249443/119079008-25863d00-b9ac-11eb-8009-75fbf01585d2.png">

<img width="530" alt="Screen Shot 2021-05-20 at 8 42 46 PM" src="https://user-images.githubusercontent.com/5249443/119079023-2b7c1e00-b9ac-11eb-8044-5bed6242a93a.png">

**Comment by ryanwoldatwork** [comment]
@maya,

Response text will now display line breaks. Please take a look when you have a chance, and let me know if you have any questions or feedback. Thanks!

**Comment by maya** [comment]
Yes, this works now, thanks!

<img width="715" alt="Screen Shot 2021-05-24 at 5 27 37 PM" src="https://user-images.githubusercontent.com/5249443/119422261-8e73fa80-bcb5-11eb-9d7b-8149068fdb99.png">
