### ISSUE TITLE
Add response content to email notification

### ISSUE THREAD

**Issue by maya** [GSA/touchpoints#487]
We'd like the email notifications to include the response content to the emails. Is this possible?

**Comment by ryanwoldatwork** [comment]
Technically possible, however this is specifically prohibited policy-wise per security posture and Touchpoints ATO , as PII may be unintentionally submitted into a form, and the goal is to not forward response contents via email.

Responses can be retrieved via [API](https://github.com/GSA/touchpoints/wiki/API) however.
