### ISSUE TITLE
check Cloud Foundry manifests into version control

### ISSUE THREAD

**Issue by afeld** [GSA/touchpoints#52]
Rather than only including [a sample](https://github.com/GSA/touchpoints/blob/master/manifest.sample.yml), can we commit the real files, taking the environment variables out? That will also mean that you aren't keeping those credentials locally in a file, which would be a good change.

**Comment by afomi** [comment]
https://github.com/GSA/touchpoints/compare/develop...manifest?expand=1

**Comment by afeld** [comment]
I suggest putting as many of the non-default [attributes](https://docs.cloudfoundry.org/devguide/deploy-apps/manifest-attributes.html) in there as you can, such as the [routes](https://docs.cloudfoundry.org/devguide/deploy-apps/manifest-attributes.html#routes).

**Comment by afomi** [comment]
@afeld - I've added the routes to the cloud.gov instances.

Would you like the cloud.gov services referenced as well?

**Comment by afeld** [comment]
The more the better!

**Comment by afomi** [comment]
@afeld - how's https://github.com/GSA/touchpoints/pull/110?

**Comment by afomi** [comment]
Manifests for Staging, Demo, and Prod have now been included.

https://github.com/GSA/touchpoints/tree/develop
