### ISSUE TITLE
BUG: Response tab counter includes archived responses count

### ISSUE THREAD

**Issue by lauraGgit** [GSA/touchpoints#521]
The parenthetical number of responses in the "Responses" tab includes the number of archived responses which is confusing. Either have it indicate that its all response or toggle between the number viewed

**Comment by ryanwoldatwork** [comment]
The number of responses will be removed the tab in an upcoming release.

**Comment by ryanwoldatwork** [comment]
The `Responses` button no longer shows total response count.

<img width="142" alt="Screen Shot 2021-07-16 at 9 00 30 AM" src="https://user-images.githubusercontent.com/64987852/125976033-c1c7b841-9dee-4ad2-b1b2-4d5d635715fa.png">
