### ISSUE TITLE
Enhancement: Publishing workflow

### ISSUE THREAD

**Issue by lauraGgit** [GSA/touchpoints#522]
After you copy an existing template you're taken to the questions tab, with little in the way of way-finding for what to do next on the survey. 

It would be a lot easier to have a next step workflow to guide you through the tabs.

In particular you have to publish a survey before you can select the delivery method, which creates the confusing current workflow of
New Survey > Copy Template > edit questions > switch tabs > Survey overview > Publish > Edit Survey > Update information in how users will update this survey > Update Survey.

It is not intuitive.

Suggested workflow:
New Survey > Copy Template > Edit questions > Save questions and be sent to delivery options > Update access of survey > Publish Survey

**Comment by ryanwoldatwork** [comment]
Delivery method can be specified (but not previewed) prior to Publishing a form.

It sounds like where the Delivery Options can be specified can be improved.

**Comment by lauraGgit** [comment]
Yes, that is part of it. It's also that the aspect of "taking you to the next step" and feels a bit choose your own adventure for someone who was creating their first form.

**Comment by ryanwoldatwork** [comment]
Hi @lauraGgit,

The UI flow has been updated, informed by your feedback. Thank you!

After copying a form, user arrives at the Forms#show page.
Questions are the next tab.
Then, Delivery Options, which includes a link to preview.

The "Publishing" interaction still deserves re-work, but some changes have been made, intended to improve the experience. The Forms "Edit" page became redundant and has been removed altogether.

Please kick the tires if you have a few minutes. I'm happy to pair and demo for you as well.

**Comment by ryanwoldatwork** [comment]
hi @lauraGgit, I'll close this out given updates to the workflow. 
Always open to additional feedback. Thank you!
