### ISSUE TITLE
Usability concern: lack of text wrapping for paragraphs in the responses table makes the "flag/archive" out of viewport

### ISSUE THREAD

**Issue by lauraGgit** [GSA/touchpoints#523]
When viewing responses online if there is a long sentence it pushes the columns so that you can now longer see the created date/ archive or flag tags

**Comment by ryanwoldatwork** [comment]
![Screen Shot 2021-06-29 at 7 22 06 AM](https://user-images.githubusercontent.com/64987852/123814686-be14b480-d8aa-11eb-95e6-bb4c1fbf0d0e.png)

Long text responses can be truncated.
Does this help?

**Comment by lauraGgit** [comment]
For one of our responses the first paragraph is super long so this doesn't fix this.

**Comment by ryanwoldatwork** [comment]
Is horizontal scroll available?

**Comment by lauraGgit** [comment]
It is available, but was working with someone who didn't see that, and missed the archive/flagged.

So that's why I raised as a usability concern rather than a bug. It's not obvious what's on that side of the table if you have a long comment.

**Comment by lauraGgit** [comment]
@ryanwoldatwork and the left actions is better, but it still cuts off longs text in a way that is hard to use

**Comment by ryanwoldatwork** [comment]
@lauraGgit - can you provide a screenshot of how the text is cutting off?

**Comment by ryanwoldatwork** [comment]
`nowrap` has been removed from the default Submissions table listing.

`nowrap` will still be applied when the user specifies `Truncation` as an option in the Submissions UI.
