### ISSUE TITLE
handling shared ownership

### ISSUE THREAD

**Issue by afeld** [GSA/touchpoints#585]
The [website inventory interface](https://touchpoints.app.cloud.gov/admin/websites) says:

> Website editing permissions are assigned to users who have an email that matches the Contact email or Site owner email of a Website.

The Tech Portfolio has (over time) maintained various lists of domains, systems, etc. From a [discussion in the now-deprecated GSA inventory](https://docs.google.com/spreadsheets/d/1OBO6g7_OsVBv0vG8WSCI6L2FD_iRh3A7a_6eQWj2zLE/edit?disco=AAAAILDgXeQ), in regards to the `Site Owner Email`:

> TTS very intentionally moved away from listing individuals since that information goes out of date so easily, lacks redundancy if that person is out, etc.

This is _especially_ the case in TTS where we do so many term hires and details. We moved to on mailing lists (Google Groups or their support email), where the teams are already maintaining their own membership. One less source of truth. All that said, not sure I have a clever idea about how best to handle that in Touchpoints.

---

Related question: For many of the sites, the contact emails are Google Groups, and site owner isn't specified. How do we get someone added to be able to edit? Perhaps there can be some other role(s) that allow editing across a swath of the site entries? Thinking for the Tech Portfolio, Office of Strategic Communications (OSC), and the Digital Councils to be able to use.

**Comment by ryanwoldatwork** [comment]
hi @afeld, 

Touchpoint now supports an Organizational Website Manager role which allows a user to edit any website record for an organization.

This role can be assigned to the groups you mentioned above. I'll follow up with you.

**Comment by afeld** [comment]
That's still a bit different than "teams own sites, not individuals," but that's useful for the Tech Portfolio, thanks!
