### ISSUE TITLE
Additional data points for consideration

### ISSUE THREAD

**Issue by RachelF** [GSA/touchpoints#590]
Hi @ryanwoldatwork Here are some more thoughts about data points - these focus on what we might want to add. Specifically, I'm interested in delving into the cost data, and bringing more of that to light.

1. To help managers better understand their digital investments, could we incorporate some specific fields from the modernization planning documents into touchpoints? Specifically, the Costs spreadsheet breaks out costs related to specific types of activities, such as UX or accessibility. Being able to see, at a glance, how much we're spending (or not!) on these activities will help teams and managers see where they may need to add support, or evaluate how well such support is improving the user experience. (For example, are they currently spending $0 on accessibility testing?) This could also help us show progress over time toward modernization and compliance w/21cIDEA.
2. I assume "modernization_cost" is the initial estimate from 2020, but can you please confirm? I like being able to track that over time, so would like to keep the year by year data.
3. Could we consider adding a way to show approval status, to tie into the new processes we're building out with the Council/Board? Show things like dates of launch, consolidation, and decommission; also maybe where it is in the approval process itself (i.e., awaiting approval by the Board). (Given that we haven't yet finalized this process, this will have to wait a bit, but wanted to get it into the backlog, if you think it's a good idea.)

Thank you!

**Comment by ryanwoldatwork** [comment]
Hi @RachelF,

Thanks for sharing these additional points.

# Item 1

I agree cost information is valuable. And yes, cost information should be factored in when assessing value. The question it prompts for me is: where should that data live?   While it is possible to create a field to track any type of information, I'd like to discuss where this data already lives and how we can use it to support website decisions. 

The Website inventory technically lists individual domains. And I'm assuming (thus need to verify/validate) that cost information would be desirable at a Product level (as opposed to 20 subdomains and staging sites tracked to constitute, (for example) Login.gov)

# Item 2

Yes, `modernization_cost` was imported from the All Websites spreadsheet `FY20 Baseline Cost` column.

# Item 3

I've started to incorporate `states` that a Website object might transition through. Here they are, recently updated.

```
PRODUCTION_STATUSES = {
    "newly_requested" => "Newly requested",
    "request_approved" => "Request approved",
    "request_denied" => "Request denied",
    "in_development" => "In development",
    "production" => "Production",
    "redirect" => "Redirect",
    "archived" => "Archived",
    "decommissioned" => "Decommissioned",
  }
  ```
  
  Happy to chat about this more and adjust, as required to support a good website lifecycle.

**Comment by ryanwoldatwork** [comment]
I'm going to close this issue.

Current states of a Website are depicted as follows.

![Screen Shot 2021-09-10 at 3 16 32 PM](https://user-images.githubusercontent.com/64987852/132923298-f5b2032c-c3a4-4c38-98ac-c877d07fc74f.png)

---

Cost information is valuable information, but the cost information doesn't seem appropriate to store in the Website Inventory.
Costs originate as finance concerns and follow-on work should explore the cost-accounting aspects of this specifically. The Website Inventory can provide data to support efforts around cost.
