### ISSUE TITLE
refining website search options

### ISSUE THREAD

**Issue by RachelF** [GSA/touchpoints#642]
Hi! I noticed that the search function seems to be case-sensitive. When I search for websites by office using lowercase letters (such as "ogp"), I get no results - but if I search for "OGP" I see all the OGP sites. Can the search parameters be updated to allow both upper and lower-case? Or some instruction added near the search box to tell people they should use upper-case when searching by office?
Thanks!

**Comment by ryanwoldatwork** [comment]
Hi @RachelF,

Thank you for the feedback and suggestion! This is complete.
