### ISSUE TITLE
Website Inventory: Change wording "Edit Website" button

### ISSUE THREAD

**Issue by anatecture** [GSA/touchpoints#651]
Users request that the language on the "edit website" button be changed. Users are concerned that the website itself will be changed by clicking that button. 

Suggested change is to "edit entry".

<img width="1342" alt="Screen Shot 2021-08-30 at 3 19 26 PM" src="https://user-images.githubusercontent.com/11577248/133309588-ceb2791c-3897-4524-9120-1aaac3aca811.png">

**Comment by ryanwoldatwork** [comment]
Not going to fix.

"Edit Objectname" is used all around the site. Clicking "Edit" doesn't update a record. Clicking "Update" does.
