### ISSUE TITLE
Change placeholder text to include an indication that it is simply placeholder

### ISSUE THREAD

**Issue by anatecture** [GSA/touchpoints#652]
Users could not understand that the light gray placeholder text was different from a real entry. 

Placeholder text needs to include an indication of its impermanence. Ideas for this could be the inclusion of "for ex." or "etc" as part of the placeholder text.

**Comment by ryanwoldatwork** [comment]
How many users?
Which text?

**Comment by anatecture** [comment]
2 users registered their confusion with the placeholder text in all the fields in which it appears. 

Removal isn't the answer: the placeholder text was found to be useful to users, as it helped them identify the nature of the field, but they didn't know that the placeholder text was simply there as examples.

**Comment by ryanwoldatwork** [comment]
https://designsystem.digital.gov/components/text-input/ advises to:

> Avoid placeholder text

**Comment by anatecture** [comment]
oh right on
