### ISSUE TITLE
Processing Separations Reports

### ISSUE THREAD

**Issue by ryanwoldatwork** [GSA/touchpoints#681]
A Separation Report is sent from IT every month, containing a list of people who have left.
If a person is listed in the Separations Report and assigned to a Website as Website Manager, what should happen?

### User Story

As a Digital Council member
I want to know which Websites do not have managers (recently, due to Separations, for example)
So that I can establish active stewardship of a website.

### Acceptance Criteria

Given a separations report is received by Touchpoints PMO
When a user is inactivated AND that user is a Website Manager or Website Contact
Then the Touchpoints PMO can easily share that information with the Digital Council and EDX team for support.

**Comment by anatecture** [comment]
I understand, and that's why it belongs in the Touchpoints backlog, not EDX. If the Touchpoints team can take this story on, fantastic, but EDX cannot.

**Comment by ryanwoldatwork** [comment]
I'm working with the Digital Council members on using Touchpoints website inventory data in their weekly operations. 
Hopefully that work brings this issue into a more actionable light.

Closing.
