### ISSUE TITLE
Modal Delivery Option Accessibility Best Practice

### ISSUE THREAD

**Issue by kah8150** [GSA/touchpoints#685]
It appears the modal delivery option injects the touchpoints button at the end of the <body> element. When running the Axe DevTools plugin (axe-core 4.3.3) it provides an accessibility best practice recommendation to make sure all content is contained by an HTML landmark (details [here](https://dequeuniversity.com/rules/axe/4.3/region?application=AxeChrome)).

Would it be possible to provide an option when using the modal delivery option to allow implementers to provide a selector for the html element to inject the touchpoints button into?

Thanks!

cc @lauraGgit

**Comment by ryanwoldatwork** [comment]
Hi @kah8150 - thanks!

Seems possible. Can you put 30 minutes on my calendar next week to discuss?

**Comment by ryanwoldatwork** [comment]
The modal is now injected into an `aside` landmark element.
