### ISSUE TITLE
Update categorization for several sites

### ISSUE THREAD

**Issue by RachelF** [GSA/touchpoints#856]
Hi! We've discovered that several sites have been miscategorized in Touchpoints.
Can you please update the following sites with the correct tags?

400yaahc.gov | "digital_brand_category=External"
advantage.gsa.gov | "production_status=redirect"
api.acquisition.gov | "type_of_site=API"
cao.gov | "production_status=redirect"
chat.18f.gov | "type_of_site=Google Form"
childtaxcredit.gov | "digital_brand_category=External"
connect.digitalgov.gov | "type_of_site=Critical Infrastructure"
discovery.gsa.gov | "production_status=redirect"
fmvrs.fas.gsa.gov | "production_status=redirect"
gsaadvantage.gsa.gov | "production_status=redirect"
mobile.reginfo.gov | "digital_brand_category=Hybrid"
tailored.fedramp.gov | "production_status=redirect"
presidentialinnovationfellows.gov | "digital_brand_category=Hybrid"
reginfo.gov | "digital_brand_category=Hybrid"
usability.gov | "production_status=archived"

Thank you! 
We also plan to follow up with additional training for site managers on how to categorize their sites.

**Comment by ryanwoldatwork** [comment]
These have been updated.
