### ISSUE TITLE
Website Inventory: Website manager semantic term

### ISSUE THREAD

**Issue by anatecture** [GSA/touchpoints#882]
As the Enterprise Digital Experience Team, we're trying to socialize the idea that we are stewards, not owners, of digital properties in the federal government. 

For this reason, we would like to replace the term "site owner" in the Touchpoints Website Inventory to "Site Lead" or "Site Program Manager"  to stipulate the person who programmatically is responsible for the site.

**Comment by ryanwoldatwork** [comment]
Hi @anatecture, 

This is in a branch, coming soon.

### base state

![image](https://user-images.githubusercontent.com/64987852/176950852-3abd1e60-f4ab-4b7c-8a36-5eccf5c22fdc.png)

### hovered state

![image](https://user-images.githubusercontent.com/64987852/176950965-1deb19e7-98b4-435b-9dc1-a12d402890dd.png)

**Comment by ryanwoldatwork** [comment]
This change has been deployed.
