### ISSUE TITLE
Registering new website managers on GSA's Website Inventory

### ISSUE THREAD

**Issue by anatecture** [GSA/touchpoints#883]
As an administrator for the GSA Website Inventory, I need to be able to list new website managers in the Inventory, but I cannot with the dropdown menu design. Please change this to include an option to create a site manager, so I can assign new GSA website managers. 

Websites I know this happening on: 
portal.fas.gsa.gov
ussm.gsa.gov
[asap.gsa.gov](http://asap.gsa.gov/)
[dashboard.data.gov](http://dashboard.data.gov/)
[fmitservices-external.gsa.gov](http://fmitservices-external.gsa.gov/)

**Comment by ryanwoldatwork** [comment]
Hi @anatecture,

Users who are typed in as Site Owner or Contact email will be available to select as a Website Manager now.

<img width="569" alt="Screen Shot 2022-06-01 at 3 08 54 PM" src="https://user-images.githubusercontent.com/64987852/171510168-33a994cf-0cad-46e4-8315-9af92aa566e9.png">

More work is in queue regarding the field definitions and UI text (eg: "owner" text will likely be updated)
