### ISSUE TITLE
Search on GSA inventory 

### ISSUE THREAD

**Issue by anatecture** [GSA/touchpoints#904]
As a user, I need to be able to search domain, email, office, sub-office, Website Manager emails, or Website Contact email. Search seems to not be permanent once the search terms have been entered.

**Comment by ryanwoldatwork** [comment]
thanks for reporting @anatecture!

**Comment by ryanwoldatwork** [comment]
Hi @anatecture,

Can you please try the search at https://touchpoints.app.cloud.gov/admin/websites when you have a chance, and let me know how it looks. Happy to hop on a call with you for this.

The search is now debounced, which has improved flashing search results. (search was being executed on every key up. now it waits 400ms).

**Comment by ryanwoldatwork** [comment]
Thanks @anatecture for confirming that this has been improved.
If you see anything else wonky in the UI, or with the UX, please share again. Thanks!
