### ISSUE TITLE
Website manager listed in table view

### ISSUE THREAD

**Issue by anatecture** [GSA/touchpoints#998]
As a user, I'd like to see the website manager listed in the table view of the Inventory
![Screen Shot 2022-08-10 at 2 35 06 PM](https://user-images.githubusercontent.com/11577248/184024769-63893ae8-3bea-4190-a7e8-82038da3bac3.png)

**Comment by ryanwoldatwork** [comment]
The primary contact is now showing instead of the additional website contacts, along with the public email address.

![image](https://user-images.githubusercontent.com/64987852/196602852-3e63aa57-3485-4e16-b66c-428acb5185a5.png)
