### ISSUE TITLE
Website manager terminology does not carry over to website entry terminology

### ISSUE THREAD

**Issue by anatecture** [GSA/touchpoints#999]
As a user, I'd need to see the term "website manager" be carried over to the website entry, instead of the term "primary website contact" to support clarity. 

**Website table view:** 
![Screen Shot 2022-08-10 at 2 35 06 PM](https://user-images.githubusercontent.com/11577248/184025262-4a1f3e4d-818e-4245-948e-94bbd61bb675.png)

**Website entry view:** 
![Screen Shot 2022-08-10 at 2 35 18 PM](https://user-images.githubusercontent.com/11577248/184025290-0bbb482a-ddbc-475b-95a9-dacf4d5e9e67.png)

**Comment by ryanwoldatwork** [comment]
`Primary contact` now shows in the table view and the form to create/edit a Website.

<img width="1129" alt="Screen Shot 2022-10-18 at 10 10 11 PM" src="https://user-images.githubusercontent.com/64987852/196735449-dcba6395-db2d-40f2-b92e-32d64d9bc71d.png">
